server:
  port: 9000

spring:
  application:
    name: hello-world-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      base-path: /api/hello/
      exposure:
        exclude: "*"