server:
  port: 9000

spring:
  application:
    name: hello-world-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  info:
    java:
      enabled: true
    env:
      enabled: true

  endpoints:
    web:
      base-path: /api/hello/
      exposure:
        include: '*'
    metrics:
      enabled: true
      jvm:
        enabled: true
      cache:
        enabled: true

  metrics:
    enable:
      process:
        files: true
    web:
      server:
        requests: true

  endpoint:
    metrics:
      web:
        server:
          requests: true
