server:
  port: 9191

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service-route
          uri: lb://employee-service
          predicates:
           - Path=/api/employees/**
        - id: employee-salary-service-route
          uri: lb://employee-salary-service
          predicates:
           - Path=/api/employeeSalaries/**
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
