server:
  port: 9001
  servlet:
    context-path: /standards
spring:
  application:
    name: standard-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/