server:
  port: 9191
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: hello-world-service-route
          uri: lb://hello-world-service
          predicates:
            - Path=/api/hello/**
            
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

