eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
management:
  endpoints:
    web:
      base-path: /api/standards/
      exposure:
        exclude: "*"