server:
  port: 9002
  servlet:
    context-path: /students
spring:
  application:
    name: student-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/